---
name: PI CEC
version: "0.3"
slug: pi_cec
description: Raspberry Pi HTTP CEC server
url: https://github.com/b3er/hassio-addons/tree/master/pi_cec
arch:
  - armv7
  - aarch64
startup: services
boot: auto
watchdog: "tcp://[HOST]:[PORT:9526]"
ports:
  "9526/tcp": null
ports_description:
  "9526/tcp": "TCP socket for outside communication (not required)"
devices:
  - "/dev/vchiq"
image: ghcr.io/b3er/{arch}-addon-pi_cec
panel_icon: mdi:video-input-hdmi
options: {}
schema: {}
video: true
