---
version: "3.0"
slug: cec_scan
name: CEC Scanner (RPI3)
url: https://github.com/b3er/hassio-addons/tree/master/cec_scan
arch:
  - armv7
  - aarch64
boot: manual
description: Scan for HDMI CEC devices
image: homeassistant/{arch}-addon-cec_scan
options: {}
schema: {}
startup: once
video: true
init: false
